# Generated by Django 4.0.4 on 2022-05-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
