# Generated by Django 4.0.4 on 2022-07-18 02:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c1d3720a-979d-4967-96aa-0152619a8819')),
        ),
    ]
