# Generated by Django 4.0.4 on 2022-07-18 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='slig',
        ),
    ]
